name: CrescentMoon
version: '${project.version}'
main: com.jack.crescentmoon.Main
api-version: 1.16
authors: [ Jack ]
description: Main project for CrescentMoon.
commands:

  givewand:
    description: Gives the custom wand to the player.
    aliases: wand
    usage: /<command>
  givepick:
    description: Gives the custom pickaxe to the player.
    aliases: pick
    usage: /<command>
  givezoro:
    description: Gives the custom zoro set to the player.
    aliases: zoro
    permission: crescentmoon.zoroset
    permission-message: §cYou do not have permission to use this!
    usage: /<command>
  givedemonslayer:
    description: Gives custom demon slayer set to the player.
    aliases: [nichirin, giveds, ds]
    usage: /<command>

  menu:
    description: Opens up the main menu gui.
    usage: /<command>

  randomtp:
    description: Randomly teleports the player to a random location on the map
    aliases: rtp
    usage: /<command>